// 커뮤니티 게시글 및 댓글 더미 데이터
export const dummyPosts = [
    {
        id: 1,
        category: 'notice',
        title: '[공지] LiveF 커뮤니티 이용규칙 안내',
        content: '커뮤니티 이용규칙을 안내드립니다.',
        user: '관리자',
        time: '1일 전',
        views: 1247,
        likes: 89,
        comments: 23,
        isNotice: true,
        isHot: false,
        tags: ['공지', '공지사항'],
    },
    {
        id: 2,
        category: 'EPL',
        title: '🔥 맨유 vs 리버풀 경기 어떻게 보셨나요?',
        content: '오늘 경기가 정말 명경기였던 것 같은데...',
        user: '축구매니아',
        time: '1시간 전',
        views: 892,
        likes: 156,
        comments: 78,
        isNotice: false,
        isHot: true,
        tags: ['HOT', 'EPL'],
    },
    {
        id: 3,
        category: 'laliga',
        title: '엠바페 레알 이적설 어떻게 생각하세요?',
        content: '최근 이적설이 많이 나오는데 실제로 가능할까요?',
        user: '레알팬',
        time: '2시간 전',
        views: 634,
        likes: 92,
        comments: 45,
        isNotice: false,
        isHot: true,
        tags: ['HOT', '라리가'],
    },
    {
        id: 4,
        category: 'free',
        title: '이번 시즌 MVP 예상해보기',
        content: '각 리그별 MVP 후보들이 누가 있을까요?',
        user: '골든부츠',
        time: '3시간 전',
        views: 423,
        likes: 67,
        comments: 34,
        isNotice: false,
        isHot: false,
        tags: ['자유게시판'],
    },
    {
        id: 5,
        category: 'bundesliga',
        title: '바이에른 vs 도르트문트 클라시코 후기',
        content: '독일 클라시코 정말 물미진진했네요',
        user: '분데스팬',
        time: '4시간 전',
        views: 567,
        likes: 89,
        comments: 29,
        isNotice: false,
        isHot: false,
        tags: ['분데스리가'],
    },
    {
        id: 6,
        category: 'seriea',
        title: '인테르 밀란 이번 시즌 어떻게 보시나요?',
        content: '챔피언스리그 진출 가능할까요?',
        user: '네라주리',
        time: '5시간 전',
        views: 345,
        likes: 43,
        comments: 18,
        isNotice: false,
        isHot: false,
        tags: ['세리에A'],
    },
    {
        id: 7,
        category: 'EPL',
        title: '손흥민 이번 시즌 득점왕 가능성?',
        content: '손흥민 선수 폼이 심상치 않네요!',
        user: '토트넘팬',
        time: '6시간 전',
        views: 222,
        likes: 31,
        comments: 12,
        isNotice: false,
        isHot: false,
        tags: ['EPL'],
    },
];

export const initialComments = [
    {
        id: 1,
        user: '축구매니아',
        content: '저도 오늘 경기 정말 재밌게 봤어요!',
        time: '30분 전',
        likes: 2,
        dislikes: 0,
        replies: [
            {
                id: 11,
                user: '리버풀팬',
                content: '리버풀 수비가 너무 불안했죠',
                time: '20분 전',
                likes: 1,
                dislikes: 0,
            }
        ]
    },
    {
        id: 2,
        user: '관리자',
        content: '커뮤니티 이용규칙을 꼭 지켜주세요!',
        time: '1시간 전',
        likes: 0,
        dislikes: 0,
        replies: []
    }
];
